### ISSUE TITLE
Fix Deadly Reentry config for the pod

### ISSUE THREAD

**Issue by BlackSoldierB** [BobPalmer/SrvPack#39]
It is generating a lot of exceptions.

[EXC 15:03:46.019] NullReferenceException: Object reference not set to an instance of an object
	DeadlyReentry.ModuleHeatShield.FixedUpdate ()
[EXC 15:03:46.019] NullReferenceException: Object reference not set to an instance of an object
	DeadlyReentry.ModuleHeatShield.FixedUpdate ()

Edit: I deleted/renamed the DRE.cfg. This fixes the errors. I am not sure if this would cause any problems

**Comment by Starwaster** [comment]
The problem here is that Deadly Reentry's ModuleHeatShield is now an extension of ModuleAblator and none of the old legacy configurations will work. I've put some fallbacks into DRE's main config file to catch that and it seems to work.

Use the same configuration you would for any ModuleAblator shield and it'll work fine.

Or if you want to make it weaker as I do for DRE, I typically use values like
```lossExp = -5000
```lossConst = 5
```pyrolysisLossFactor = 40

for a Mk1pod so it's mostly LKO survivable. Up to you though!

**Comment by BobPalmer** [comment]
Closing as the pod got a refresh, deprecating the DRE config
